# Generated by Django 5.1.2 on 2024-10-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0003_pessoa_tipo_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteracoesPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primeiro_app.pessoa')),
            ],
        ),
    ]
