<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-11-04 23:27
=======
# Generated by Django 5.1.2 on 2024-10-29 01:00
>>>>>>> a8f3bd1c98808b5d62bf027961296369efe5f884

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0004_interacoespessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
