# Generated by Django 5.1.2 on 2024-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0005_categoriadespesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Alimentação', 'alimentação'), ('Compras', 'compras'), ('Contas', 'contas'), ('Lazer', 'lazer')], max_length=45, null=True)),
            ],
        ),
    ]
