# Generated by Django 5.1.2 on 2024-11-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0005_categoriadespesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasReceitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='categoriadespesas',
            name='categoria_predefinida',
            field=models.CharField(blank=True, choices=[('Alimentação', 'alimentação'), ('Compras', 'compras'), ('Contas', 'contas'), ('Lazer', 'lazer')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='categoriadespesas',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriadespesas',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
