# Generated by Django 5.1.2 on 2024-11-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0006_categoriasreceitas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, choices=[('Alimentação', 'alimentação'), ('Compras', 'compras'), ('Contas', 'contas'), ('Lazer', 'lazer')], max_length=45, null=True, verbose_name='CategoriaPredefininida')),
            ],
        ),
        migrations.AlterField(
            model_name='categoriadespesas',
            name='categoria_predefinida',
            field=models.CharField(blank=True, choices=[('Alimentação', 'alimentação'), ('Compras', 'compras'), ('Contas', 'contas'), ('Lazer', 'lazer')], max_length=45, null=True, verbose_name='CategoriaPredefininida'),
        ),
    ]
