# Generated by Django 5.1.2 on 2024-11-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0007_categoriadespesas_predefinida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriadespesas',
            name='predefinida',
        ),
        migrations.AlterField(
            model_name='categoriadespesas',
            name='nome',
            field=models.CharField(choices=[('Alimentação', 'Alimentação'), ('Compras', 'Compras'), ('Contas', 'Contas'), ('Lazer', 'Lazer')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
