# Generated by Django 5.1.2 on 2024-11-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0008_remove_categoriadespesas_predefinida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadespesas',
            name='predefinida',
            field=models.CharField(blank=True, choices=[('Alimentação', 'alimentação'), ('Compras', 'compras'), ('Contas', 'contas'), ('Lazer', 'lazer')], max_length=45, null=True, verbose_name='CategoriaPredefinida'),
        ),
        migrations.AlterField(
            model_name='categoriadespesas',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoriapredefinida',
            name='nome',
            field=models.CharField(choices=[('Alimentação', 'alimentação'), ('Compras', 'compras'), ('Contas', 'contas'), ('Lazer', 'lazer')], default=1, max_length=45),
            preserve_default=False,
        ),
    ]
