# Generated by Django 5.1.2 on 2024-11-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0009_categoriadespesas_predefinida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasReceitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
