# Generated by Django 5.1.2 on 2024-11-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0010_categoriasreceitas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaPredefinida',
        ),
    ]
