# Generated by Django 5.1.2 on 2024-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0011_delete_categoriapredefinida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriadespesas',
            name='predefinida',
        ),
        migrations.AddField(
            model_name='categoriadespesas',
            name='cat_predefinida',
            field=models.CharField(blank=True, choices=[('Alimentação', 'alimentação'), ('Compras', 'compras'), ('Contas', 'contas'), ('Lazer', 'lazer')], max_length=45, null=True),
        ),
    ]
